[tool.bumpversion]

current_version = "2513"
allow_dirty = true

parse = """(?x)
    (?P<release>
        (?:[0-9]{2})
        (?:[1-9ABC])
        (?:[1-9A-V])
    )
    (?:\\.(?P<patch>[1-9][0-9]*))?
"""
parts = { release = { calver_format = "{YY}{M62}{D62}" } }
serialize = ["{release}.{patch}", "{release}"]

files = [
  {filename = "DOCKERHUB.md"},
  {filename = "README.md"},
  {filename = "docker-bake.hcl"},
  {filename = "bin/py.sh"},
  {filename = "tests/share/info/base.json"},
  {filename = "tests/share/info/latest.json"},
  {filename = "tests/share/info/stable.json"},
  {filename = "tests/share/info/supported.json"},
  {filename = "tests/share/info/test_readme_advanced.json"},
]
