target-version = "py313"

[lint]
select = ["E4", "E7", "E9", "F", "B", "S"]
per-file-ignores."docsubfile.py" = [
  "S603",  # `subprocess` call: check for execution of untrusted input
  "S607",  # Starting a process with a partial executable path
]

[format]
quote-style = "single"
docstring-code-format = true
docstring-code-line-length = "dynamic"
