version: '3'

vars:
  IMG: makukha/multipython
  RELEASE: {sh: yq -oy '.tool.bumpversion.current_version' .bumpversion.toml}

tasks:

  checkupd:
    desc: Check for version updates.
    cmds:
      - docker buildx bake pyenv
      - docker run --rm -t makukha/multipython:pyenv py_checkupd

  lint:
    desc: Run linters.
    cmds:
      - hadolint Dockerfile tests.dockerfile
      - shellcheck *.sh

  build:
    desc: Build base docker images.
    cmds:
      - docker buildx bake --no-cache pyenv
      - docker buildx bake --no-cache py multipython

  clean:
    desc: Prune local tags, images, and build cache.
    cmds:
      - cmd: docker image rm --no-prune makukha/multipython
        ignore_error: true
      - cmd: 'docker image rm --no-prune makukha/multipython:{{.ITEM}}'
        for: { var: TAGS }
        ignore_error: true
      - docker image prune
      - docker builder prune

  shell:*:
    desc: Shell to image {pyenv,tox,py*,latest}.
    cmds:
      - docker run --rm -it {{.IMG}}:{{index .MATCH 0}} /bin/bash

  test:
    desc: Run tests.
    cmds:
      - docker buildx bake --no-cache tests

  version:
    desc: Bump release version.
    cmds:
      - bump-my-version bump --dry-run --verbose release
      - task: version:bump

  version:bump:
    internal: true
    prompt: The version will be bumped as above. Continue?
    cmds:
      - bump-my-version bump release

  release:
    desc: Push base images to Docker Registry.
    prompt: Releasing pyenv, single version, and multipython images. Continue?
    status:  # guard against overwriting
      - docker pull {{.IMG}}:{{.RELEASE}}
    cmds:
      - docker buildx bake --push pyenv py multipython
