version: '3'

vars:
  IMG: makukha/multipython
  RELEASE: {sh: yq -oy '.tool.bumpversion.current_version' .bumpversion.toml}

tasks:

  checkupd:
    desc: Check for version updates.
    cmds:
      - docker buildx bake base
      - docker run --rm -t {{.IMG}}:base py_checkupd

  lint:
    desc: Run linters.
    cmds:
      - hadolint Dockerfile tests/Dockerfile
      - shellcheck *.sh tests/*.sh

  build:
    desc: Build all docker images.
    cmds:
      - docker buildx bake
      - docker run --rm {{.IMG}}:latest py info -c > info.json

  build:base:
    desc: Build base docker image.
    cmds:
      - docker buildx bake base

  clean:
    desc: Prune local tags, images, and build cache.
    vars:
      TAGS:
        sh: docker image ls --format json | jq -r '. | select(.Repository == "{{.IMG}}") | .Tag'
    cmds:
      - cmd: docker image rm {{.IMG}}
        ignore_error: true
      - cmd: 'docker image rm {{.IMG}}:{{.ITEM}}'
        for: { var: TAGS }
        ignore_error: true
      - docker image prune
      - docker builder prune

  shell:*:
    desc: Shell to image {base,tox,py*,latest}.
    cmds:
      - docker run --rm -it {{.IMG}}:{{index .MATCH 0}} /bin/bash

  run:*:
    desc: Run command in image {base,py*,latest} container.
    cmds:
      - docker run --rm -it {{.IMG}}:{{index .MATCH 0}} {{.CLI_ARGS}}

  test:
    desc: Run tests.
    env:
      BUILDKIT_PROGRESS: plain
    cmds:
      - docker buildx bake --no-cache test

  version:
    desc: Bump release version.
    cmds:
      - uvx bump-my-version bump --dry-run --verbose release
      - task: version:bump

  version:bump:
    internal: true
    prompt: The version will be bumped as above. Continue?
    cmds:
      - uvx bump-my-version bump release

  release:
    desc: Push base images to Docker Registry.
    prompt: Release all images. Continue?
    status:  # guard against overwriting
      - docker pull {{.IMG}}:{{.RELEASE}}
    cmds:
      - docker buildx bake --push
