version: '3'

vars:
  IMG: makukha/multipython

tasks:

  build:
    desc: Build and test docker image.
    cmds:
      - docker buildx bake {{.OPT}} pyenv tox #py
#      - docker buildx bake {{.OPT}} final

  rebuild:
    desc: Same as build but with --no-cache.
    cmds:
      - {task: build, vars: {OPT: --no-cache}}

  shell:*:
    desc: Shell to image {pyenv,tox,py*,latest}.
    cmds:
      - docker run --rm -it {{.IMG}}:{{index .MATCH 0}} /bin/bash

  test:
    desc: Run tests.
    cmds:
      - docker buildx bake --no-cache tests

  version:show:
    desc: Show version bump tree.
    cmds:
      - bump-my-version show-bump

  version:bump:
    desc: Bump release version.
    cmds:
      - bump-my-version bump --dry-run --verbose release
      - task: version:bump:do

  version:bump:do:
    internal: true
    prompt: The version will be bumped as above. Continue?
    cmds:
      - bump-my-version bump release

  release:
    desc: Push image to Docker Hub.
    status:
      - docker pull {{.IMG}}:{{.VER}}
    cmds:
      - task: clean:tags
      - task: build
      - task: test
#      - docker push {{.IMG}}:{{.VER}}
#      - docker push {{.IMG}}:latest

  clean:tags:
    desc: Remove all local tags but keep images.
    vars:
      TAGS: {sh: 'docker image ls {{.IMG}} --format="{{`{{.Tag}}`}}" | sed -e"s/<none>//" | sort -u'}
    cmds:
      - cmd: docker image rm --no-prune makukha/multipython
        ignore_error: true
      - cmd: 'docker image rm --no-prune makukha/multipython:{{.ITEM}}'
        for: {var: TAGS}
        ignore_error: true
